import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], display: "swap", weight: "400" });

export const metadata = {
  title: "ABC HOME PAGE",
  description: "Generated by create next app for abc website",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
